"""empty message

Revision ID: 5b3e74fdf975
Revises: 29a7708b508b
Create Date: 2022-04-14 18:38:37.145458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3e74fdf975'
down_revision = '29a7708b508b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('quote', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'approved')
    op.drop_column('person', 'approved')
    # ### end Alembic commands ###
